### ISSUE TITLE
Cant create Banking rules nor Junk Rules

### ISSUE THREAD

**Issue by Yazller** [klingo/ESO-PersonalAssistant#363] opened 2021-04-30 21:16 UTC
I reinstalled the addon today and now I cant create any bank or junk rules, because the game don't give me the option when I right click on the items.

**Comment by Yazller** [comment] 2021-04-30 22:05
Found the issue, the Dolgubon's Lazy Writ Crafter addon is making the bank/junk rule text on items don't appear, when I turn it off I can set rules. 

Can you investigate this?

**Comment by klingo** [comment] 2021-05-01 14:23
There is nothing I can do on my side - the problem is with the "DolgubonsLazyWritCreator" addon - it also breaks other addons such as FCOItemSaver.

It can only be fixed by the author of "DolgubonsLazyWritCreator".

You can manually fix it as well, for that please check the latest comments on the LazyWritCreator addon page:
https://www.esoui.com/downloads/info1346-DolgubonsLazyWritCrafter.html#comments

![image](https://user-images.githubusercontent.com/14639044/116785386-96b38e00-aa99-11eb-91d5-14500a931adf.png)

**Closed as completed** 2021-05-01 14:24 UTC
Labels: wontfix-wontdo
