### ISSUE TITLE
Auto mark {Treasure} As Junk

### ISSUE THREAD

**Issue by TheHiveHelixLabs** [klingo/ESO-PersonalAssistant#229] opened 2020-01-18 04:29 UTC
IT simply does not work....... my bag is full of Treasure items because it was not junking them like it was supposed to.....

**Comment by klingo** [comment] 2020-02-20 21:22
Can you please be a bit more specific? Have you maybe the Quest Protection for Treasure Items enabled? This will prevent certain Treasure Items from being marked as junk.

**Comment by klingo** [comment] 2020-10-04 21:09
Did not get any further feedback and cannot reproduce issue --> closed

**Closed as completed by klingo** 2020-10-04 21:09 UTC
Labels: need-more-information, wontfix-wontdo
